language: node_js
os: linux

before_install:
  - echo "//npm.dusk.network:4873/:_authToken="${NPM_TOKEN}"" > .npmrc

before_script:
  - yarn sb:build

script:
  - echo "skipping tests"

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: storybook-static
  repo: dusk-network/dusk-ui-kit
  target_branch: gh-pages
  on:
    branch: master
